apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: ipmr6tizt-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: ipmr6tizt-go 
  name: ipmr6tizt-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: ipmr6tizt-go 
